<!doctype html>
<html>
	<head>
		<meta charset="utf-8">

		<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

		<link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,800italic,400,700,800'>
		<link rel="stylesheet" href="/media/css/style.css">
		<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=visualization&key=AIzaSyBBKVTfyoEeTYBf2ou92L85S15mFpWHdQ8&sensor=false"></script>
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
		<script src="/js/angular.js"></script>
		<script src="/js/angular-resource.js"></script>
		<script src="/js/mapDataController.js"></script>
		<script src="http://cdn.sockjs.org/sockjs-0.3.min.js"></script>
		<script src="/js/app.js"></script>
		<title>The Big One</title>
	</head>
	<body>
		<header>
			<hgroup>
				<h1>Centrale operativa</h1>
			</hgroup>
		</header>
		{% block content %}{% endblock %}
	</body>
</html>